-- Create the BOOK table if it does not exist.
-- This keeps repeated workshop starts safe.

-- TODO: Workshop task 2
-- Add CATEGORY column and adjust inserts/selects to pass category through the stack.
-- For now, keep the base BOOK schema without CATEGORY.

DECLARE
    v_table_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_table_count
      FROM USER_TABLES
     WHERE TABLE_NAME = 'BOOK';

    IF v_table_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE BOOK (
                ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                TITLE VARCHAR2(200) NOT NULL,
                AUTHOR VARCHAR2(200) NOT NULL,
                ISBN VARCHAR2(50)
            )';
    END IF;
END;
