-- Create the BOOK table if it does not exist.
-- If the table already exists, add CATEGORY if it is missing.
-- This keeps repeated workshop starts safe.

DECLARE
    v_table_count NUMBER;
    v_category_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_table_count
      FROM USER_TABLES
     WHERE TABLE_NAME = 'BOOK';

    IF v_table_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE BOOK (
                ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                TITLE VARCHAR2(200) NOT NULL,
                AUTHOR VARCHAR2(200) NOT NULL,
                ISBN VARCHAR2(50),
                CATEGORY VARCHAR2(100)
            )';
    ELSE
        SELECT COUNT(*)
          INTO v_category_count
          FROM USER_TAB_COLUMNS
         WHERE TABLE_NAME = 'BOOK'
           AND COLUMN_NAME = 'CATEGORY';

        IF v_category_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE BOOK ADD CATEGORY VARCHAR2(100)';
        END IF;
    END IF;
END;
