-- Schema for manual setup of the workshop BOOK table in Oracle.
-- Keep this aligned with the automatic startup scripts in:
-- - src/main/resources/sql/01_book_schema.sql
-- This file is intended for one-off manual setup in the DB container.
-- Re-running it as-is can fail with:
-- ORA-00955: name is already used by an existing object.
-- For repeatable startup behavior, use:
-- src/main/resources/sql/01_book_schema.sql

CREATE TABLE BOOK (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL,
    AUTHOR VARCHAR2(200) NOT NULL,
    ISBN VARCHAR2(50)
);
